hyperskill_project:
  id: 68
  ide_files: https://stepik.org/media/attachments/lesson/219111/additional_files.json
  is_template_based: false
  use_ide: true
update_date: Thu, 01 Jan 1970 00:00:00 UTC
stages:
- id: 366
  step: 5790
  is_completed: true
- id: 367
  step: 5791
  is_completed: false
- id: 368
  step: 5792
  is_completed: false
- id: 369
  step: 5793
  is_completed: false
- id: 370
  step: 5794
  is_completed: false
- id: 371
  step: 5795
  is_completed: false
